# Generated by Django 2.0.3 on 2020-06-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200621_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('name', 'kind')},
        ),
    ]
