# Generated by Django 2.0.3 on 2020-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200622_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haspricedinner',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='haspricedinner',
            name='size',
        ),
        migrations.RemoveField(
            model_name='haspricepizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='haspricepizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='haspricesub',
            name='size',
        ),
        migrations.RemoveField(
            model_name='haspricesub',
            name='sub',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='sizes',
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplatter',
            unique_together={('name', 'size')},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sizes',
        ),
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('name', 'kind', 'size')},
        ),
        migrations.RemoveField(
            model_name='sub',
            name='sizes',
        ),
        migrations.AlterUniqueTogether(
            name='sub',
            unique_together={('name', 'size')},
        ),
        migrations.DeleteModel(
            name='hasPriceDinner',
        ),
        migrations.DeleteModel(
            name='hasPricePizza',
        ),
        migrations.DeleteModel(
            name='hasPriceSub',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
