# Generated by Django 2.0.3 on 2020-06-23 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_auto_20200623_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingCartItem',
        ),
    ]
