# Generated by Django 2.0.3 on 2020-06-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='no_toppings',
        ),
    ]
